---
# tasks file for package_remove
- name: This task does package installations
  yum:
    name: "{{ packagelist }}"
    state: absent
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
