---
# tasks file for syslog_updates
- name: adding text
  blockinfile:
    path: /etc/rsyslog.conf
    insertafter: EOF
    backup: yes
    state: present
    block: |
      $FileCreateMode 0640
- name: file permssions
  file:
    path: /etc/rsyslog.d
    mode: '0640'
    owner: root
    group: root
    recurse: yes
- name: permission on log
  file:
    path: /var/log
    mode: '0775'
  notify: restart-rsyslog
